### ISSUE TITLE
Color selected words

### ISSUE THREAD

**Issue by evilcel3ri** [dillonchanis/theme-midnight-city#1]
Hi!

Love your theme. It's really one of my favorites! I have one little issue is that it doesn't color selected words. Here is are one screenshot with Midnight theme and one with the default VSCode dark theme:
VSCode dark:
![Screenshot from 2019-07-09 10-36-39](https://user-images.githubusercontent.com/3540752/60872795-9e0b0700-a235-11e9-90ad-7a9be3c18ccb.png)
Midnight City:
![Screenshot from 2019-07-09 10-36-22](https://user-images.githubusercontent.com/3540752/60872796-9ea39d80-a235-11e9-95e9-c4a8328044ed.png)

Thank you and have a nice day!

**Comment by dillonchanis** [comment]
Hey @christalib,

Thank you for using my theme and taking the time to fill out this issue! I agree, looking at the screenshots side by side it is definitely an issue.  I'll boost up the contrast between the purple highlight and the text. I should have something by the end of the day.

**Comment by evilcel3ri** [comment]
That's amazing, thank you for your quick response and thank you for the fix!

Looking forward to your fix :tada:

**Comment by dillonchanis** [comment]
Hey @christalib, currently working on this. Since you've brought up the issue I'd love to get your opinion on the proposed solution.

Updated the selection color in general to be more noticeable. Matching selections are a bit lighter than the normal selection.

<img width="766" alt="Screen Shot 2019-07-09 at 7 58 17 PM" src="https://user-images.githubusercontent.com/12295922/60930554-20221c80-a284-11e9-9193-8775ea922829.png">

**Comment by evilcel3ri** [comment]
Hi! 

Thank you for asking! So I feel the contrast between the two colors might be a bit too close to each other. Do you think you can make the matching selections a bit lighter? Does it works well on a whole page of text or code?

It seems too similar on one of my screen but the colors might be off on this one.

**Comment by dillonchanis** [comment]
Hey, got caught up yesterday. Lightened it up a bit and put it toward more gray side.

Short example:
<img width="1010" alt="Screen Shot 2019-07-11 at 7 53 20 PM" src="https://user-images.githubusercontent.com/12295922/61092872-03b5e980-a416-11e9-83fa-bf59ba3ff1dc.png">

Longer one:
<img width="1021" alt="Screen Shot 2019-07-11 at 7 53 42 PM" src="https://user-images.githubusercontent.com/12295922/61092879-0b758e00-a416-11e9-8f8f-1b7c5c7bc78d.png">

**Comment by evilcel3ri** [comment]
Hi! No problems :)

Looks cool! Looking forward to try it. Thank you very much!

**Comment by dillonchanis** [comment]
Just published a new version with the above changes.  Thanks again for taking the time to make this issue and give your opinions.  I really appreciate it!
