### ISSUE TITLE
Conflict with Jupyter Extension

### ISSUE THREAD

**Issue by edward-coombes** [dillonchanis/theme-midnight-city#10]
When using the VS code Jupyter extension the cursor is the same color as the background.

With Midnight City Theme enabled:
![image](https://user-images.githubusercontent.com/27023712/104041804-92d8c480-51a7-11eb-9c2e-39494ba01f25.png)

With Midnight City Theme disabled:
![image](https://user-images.githubusercontent.com/27023712/104041928-c582bd00-51a7-11eb-8760-1f005b452c46.png)

**Comment by dillonchanis** [comment]
I'm not too familiar with Jupyter but I'll try to reproduce this weekend and get a fix in. Thanks for letting me know!

**Comment by dillonchanis** [comment]
Hey just pushed up a change. The current version should be `0.6.0` now so I'd reinstall + reload VSCode and it should be working now!

<img width="379" alt="Screen Shot of Jupyter in Midnight City" src="https://user-images.githubusercontent.com/12295922/104106941-fd146680-5286-11eb-9f2e-ec28cc709e28.png">
