### ISSUE TITLE
color problem 

### ISSUE THREAD

**Issue by Mres01** [dillonchanis/theme-midnight-city#13]
I used this extension around 5 months ago but now when i installed vscode again and i added this extension again it dose not have the same color as before.  
![Screenshot 2022-12-03 201513](https://user-images.githubusercontent.com/119745304/205458407-d9a16784-0be4-4082-9be6-40e3ef20e099.jpg)

this is how it used to be but now the colors are different, please introduce me if there is another extension with these colors, because I was writing an educational project in Python and half of the project was written with this color scheme.

**Comment by dillonchanis** [comment]
Hey @Mres01, not sure what the issue is here tbh. As you can tell I haven't updated this in years since it's been pretty stable and I was happy with the color choices. The only thing I could think of is perhaps another extension causing an issue?

**Comment by Mres01** [comment]
> Hey @Mres01, not sure what the issue is here tbh. As you can tell I haven't updated this in years since it's been pretty stable and I was happy with the color choices. The only thing I could think of is perhaps another extension causing an issue?

Hey @dillonchanis , Thank you for the reply.
Yes it's possible, in 24h i tried all extension with similar name but  none of them were what I wanted, the problem is i copied the codes from vscode to world because I was writing a Python language training Word file, Now, if I use another color scheme, the codes that i copied in Word will not have same color as the new codes.

**Comment by Mres01** [comment]
@dillonchanis Now I try to make my own theme but it's to complicated for me, i tried to do with 

{
"Workbench.colorcustomizations": {
}
}

I changed some buttons color and background but i can't change the text color like, variables, strings, numbers and ... 

I would be grateful if you could help me how I can apply my coloring.

**Comment by dillonchanis** [comment]
@Mres01 You could try taking a look at https://github.com/dillonchanis/theme-midnight-city/blob/master/src/midnight-city.yml to get the "token" names for the values you want to change. You might have some luck references other themes too to get ideas such as [Night Owl](https://github.com/sdras/night-owl-vscode-theme/blob/main/themes/Night%20Owl-Light-color-theme.json )

**Comment by Mres01** [comment]
Thank you so much @dillonchanis, it were so useful, im almost done but i cant find scope command for variable quoted, statements, mathematical operations symbols and bracket.
I could choose two different color for string quoted and string unquoted, but for variables i could choose only one color for both variable quoted and variable unquoted. If you know how can i find those scope commands please tell me.
