### ISSUE TITLE
New pink is very strong

### ISSUE THREAD

**Issue by evilcel3ri** [dillonchanis/theme-midnight-city#2]
Hi! 

Love the selected word colors, thank you so much for that. I saw that there was an update for the selection color (pink), I don't know if it was part of the fix you did for the previous issue or not. 

Anyway, it looks different between HTML or other programming languages. I tried in Go and Python and the blue for functions names has a very strong contrast with the pink used for selection.

![Screenshot from 2019-07-15 10-20-31](https://user-images.githubusercontent.com/3540752/61203481-c342be00-a6ea-11e9-881e-8cb363947a3c.png)
![Screenshot from 2019-07-15 10-25-22](https://user-images.githubusercontent.com/3540752/61203511-df465f80-a6ea-11e9-818f-54ce57e33135.png)

Do you have the same issue on your screen?

Is that linked with the previous fix? If so, I'm terribly sorry. 

Have a nice day!

**Comment by dillonchanis** [comment]
Hey @christalib,

I'm an idiot. This pink was the one of the options I was considering and decided against it when playing with different selection colors.  I guess I never ended up removing it.  I've been in Figma so I haven't even noticed it myself.  I'll push out a quick update so its that purple we decided on last issue.  Thanks again!

**Comment by dillonchanis** [comment]
Just pushed up a new version `0.3.0` that should fix this back in our original [issue](https://github.com/dillonchanis/theme-midnight-city/issues/1)!

**Comment by evilcel3ri** [comment]
Works like a charm! Thank you very much for this quick answer!
