### ISSUE TITLE
UI Settings does not show borders for check boxes

### ISSUE THREAD

**Issue by bmidi** [dillonchanis/theme-midnight-city#3]
![image](https://user-images.githubusercontent.com/41168671/61804000-22968180-ae01-11e9-955a-c4cd2780ea9c.png)

Using the UI Settings in VSCode, it appears that checkbox borders do not show up due to conflicting color scheme.

**Comment by bmidi** [comment]
You can see in other themes that the checkbox border (or drop shading) is apparent:
![image](https://user-images.githubusercontent.com/41168671/61804243-92a50780-ae01-11e9-9569-ff556144daae.png)

**Comment by dillonchanis** [comment]
Hey @bustelyo,

Thanks for opening this issue! I'm a little busy today/tomorrow but I'll definitely take a look at it Friday.

**Comment by bustelyo** [comment]
No problem! As this is my favorite theme I thought I'd give it a go adding some base theme color palette fixes to checkboxes and decided to add them to the scrollbar too. I've read and stepped through your contributing guidelines but cannot add the branch due to permission denied.

**Comment by dillonchanis** [comment]
Thanks again for your PR! 

Fixed with #4.
