### ISSUE TITLE
Boxes and select colors very purple

### ISSUE THREAD

**Issue by evilcel3ri** [dillonchanis/theme-midnight-city#5]
Hi mate! Hope you're fine. There has been some changes in the theme and I was wondering if this stronger color was coming from #4 

![Screenshot from 2019-08-06 13-08-20](https://user-images.githubusercontent.com/3540752/62536806-373a3700-b84f-11e9-8e4e-0ed285fe6e9c.png)
![Screenshot from 2019-08-06 13-31-49](https://user-images.githubusercontent.com/3540752/62536811-3bfeeb00-b84f-11e9-8f29-b6c6fb3b9a4a.png)

Thanks and have a nice day!

**Comment by dillonchanis** [comment]
@christalib Yes it was introduced in that PR.  I think it could be toned down a bit, I typically don't have my screen brightness all the way up and noticed it was pretty bright as well.  I'll take a look at it more closely tomorrow.

**Comment by dar5hak** [comment]
Even with low screen brightness, I find the foreground-background contrast rather low, making the text less readable. Something like #9775c7 or #8466ae could work probably?

**Comment by dillonchanis** [comment]
Sorry all, been really busy the past few weeks. @dar5hak I agree, I do like that second color. Let me give it a shot locally and I should push up a change today!

**Comment by dillonchanis** [comment]
Solved in #6 

Contrast between BG and FG colors passes accessibility standards.

**Comment by dar5hak** [comment]
Thanks a lot, Dillon! You just made Easymotion even easier for me. :smiley:

**Comment by evilcel3ri** [comment]
thanks!
