### ISSUE TITLE
iTerm2 Colors

### ISSUE THREAD

**Issue by Chirag-Khandelwal** [dillonchanis/theme-midnight-city#7]
Hey!

This is an amazing color scheme.
Couldn't find an equivalent for iTerm2, so I made my own (attached).
There are probably some hiccups and rough edges though.
Added screenshot.

You mind if I publish it on a repository?
Or would you want to publish it yourself?

[Midnight-City.zip](https://github.com/dillonchanis/theme-midnight-city/files/4736069/Midnight-City.zip)

<img width="782" alt="Screen Shot 2020-06-05 at 17 55 35" src="https://user-images.githubusercontent.com/18194713/83876047-cce77100-a755-11ea-8cd2-7b344b4587ec.png">

Cheers,
Electrux

**Comment by dillonchanis** [comment]
Hey @Electrux! This looks awesome! You can totally publish it, let me know and I can throw up a link on this repo's README.

**Comment by Chirag-Khandelwal** [comment]
That's great!
I have published it here: https://github.com/Electrux/iterm2-midnight-city 😁 
It would be really nice of you to link it in README 😊

Cheers,
Electrux

**Comment by dillonchanis** [comment]
Added to README in #8 

Thank you again, looks awesome!
